name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps:
      #  any step runs will run in container
      - name: Log node node-version
        run: |
          node -v
          cat /etc/os-release


