name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest]
        node_version: [6,8,10]
        include:
        #  to include extra input config to martix for a particular job combination
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu: "true"
        exclude:
        #list the jobs to exclude
        # input combination to excluse
          - os: ubuntu-latest
            node_version: 6
          - os: windows-latest
            node_version: [6,10]
      max-parallel: 0
      fail-fast: true
    runs-on: ${{matrix.os}}
    env:
      IS_UBUNTU_8: ${{matrix.is_ubuntu}}
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node_version: ${{matrix.node_version}}
      - name: Log node node-version
        run: node -v
      - name: Log IS_UBUNTU_8
        run: echo $IS_UBUNTU_8
